siteTitle = "Blog by Sean Cha"
siteDescr = "Coder & Cinephile, HKUST"
siteAuthor = "Sean Cha"

siteGithubUrl = "https://github.com/tea1528"
siteEmailUrl = "scha@connect.ust.hk"
siteLinkedIn = "https://linkedin.com/tea1528"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
blogUrl = "https://seancha.netlify.com"
disqusShortname = "gatsby-blog"
